### PR TITLE
added proper support text

### PR DESCRIPTION
**Pull request by hamza72x**

### CODE REVIEW

**Review by withzombies — CHANGES_REQUESTED** [review]
I don't know if we should merge this change. It really depends on if we're considering lmao to be an acronym or initialism. I know some people who treat it as an acronym. According to Chicago-style, we'd keep it lowercase as an acronym.

"lmao", as the kids today say.

**Comment by moyix** [comment]
I'm also concerned that writing "LMAO" implies a level of effort I'm not willing to put in. After all, if I've got time to use the shift key, why don't I have time to help debug your issue, huh?

**Comment by hamza72x** [comment]
> I'm also concerned that writing "LMAO" implies a level of effort I'm not willing to put in. After all, if I've got time to use the shift key, why don't I have time to help debug your issue, huh?

💐 😅

**Review by w3bdesign — CHANGES_REQUESTED** [review]
`LMAO (Laughing my ass off)`  should be used so that older people can understand it as well  ;-)

**Comment by mahmudz** [comment]
Getting watch notifications on this silly topic, I think this pull request should be closed. @moyix

**Comment by moyix** [comment]
Gotcha, don't want to annoy people! :)

**Pull request closed without merging**
