### PR TITLE
feat:  support an web-based FauxPilot client

### PR DESCRIPTION
**Pull request by leemgs**
This PR is to support the feature that was issued at #88.
It aims to establish the CURL and PHP-based web Client that uses the REST API as a client.
Through the following installation procedures, you can quickly request the service and evaluate the processing results.
```bash
$ sudo apt -y install php php-common php-pear php-mbstring php-curl
$ chmod 400 ./conf/config.ini
$ vi ./conf/config.ini
$ php -S 0.0.0.0:5555
$ firefox http://localhost:5555
````

Geunsik Lim (12):
  Added output interface of web client
  Added style sheet for html design
  Added pop-up window to generate help message
  Added header file as a common UI
  Added error handling routine to avoid unexpected issues
  Added clipboard function to use inference result
  Added java-script file to handle messages
  Added index.html file to handle entrance of web-browser
  Added README.md file for documentation
  Added image files to show screenshot and icons
  Added 'conf' directory to manage configuration information
  Added how to install web-based client in existing client.md

 client/README.md         |  27 ++++++++
 client/client.js         |  54 ++++++++++++++++
 client/clipboard.php     |  16 +++++
 client/conf/config.ini   |  12 ++++
 client/err_handle.php    |  14 +++++
 client/header.php        |  16 +++++
 client/help.php          |  32 ++++++++++
 client/img/circle.png    | Bin 0 -> 7638 bytes
 client/img/fauxpilot.png | Bin 0 -> 13210 bytes
 client/img/help.png      | Bin 0 -> 5230 bytes
 client/img/input.png     | Bin 0 -> 56039 bytes
 client/img/notice.png    | Bin 0 -> 2362 bytes
 client/img/output.jpg    | Bin 0 -> 34224 bytes
 client/img/output.png    | Bin 0 -> 50756 bytes
 client/img/progress.gif  | Bin 0 -> 1057485 bytes
 client/index.html        |  14 +++++
 client/output.php        | 131 +++++++++++++++++++++++++++++++++++++++
 client/style.css         |  33 ++++++++++
 documentation/client.md  |   7 ++-
 19 files changed, 355 insertions(+), 1 deletion(-)
 create mode 100644 client/README.md
 create mode 100644 client/client.js
 create mode 100644 client/clipboard.php
 create mode 100644 client/conf/config.ini
 create mode 100644 client/err_handle.php
 create mode 100644 client/header.php
 create mode 100644 client/help.php
 create mode 100644 client/img/circle.png
 create mode 100644 client/img/fauxpilot.png
 create mode 100644 client/img/help.png
 create mode 100644 client/img/input.png
 create mode 100644 client/img/notice.png
 create mode 100644 client/img/output.jpg
 create mode 100644 client/img/output.png
 create mode 100644 client/img/progress.gif
 create mode 100644 client/index.html
 create mode 100644 client/output.php
 create mode 100644 client/style.css

--
2.17.1

Signed-off-by: Geunsik Lim <leemgs@gmail.com>
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
## Self-assessment (Demo)

[https://www.youtube.com/watch?v=m1-98NDLScs)

**Comment by leemgs** [comment]
The screenshot below shows the web-based client's instruction manual after this PR.

* Screenshot: 
image

**Comment by leemgs** [comment]
Now that one week (7days) has passed, I will comment on the "RESNED V2" notification as follows for review process. :)

RESNED V2.

**Comment by moyix** [comment]
I really like the idea, but just for maintenance reasons I think I would prefer that add-on projects like this go in their own repos (I have a hard enough time keeping up with PRs for the core project!). I’d be happy to link to them in the documentation and in a “Featured Projects” page on the Wiki though!

**Comment by leemgs** [comment]
First of all, thank you so much for reviewing in detail despite your busy schedule.
As you said, I agree to classify it as an add-on project and maintain it.
So I would like to suggest two methods as follows.

1. Can I create an add-on or ext folder on this org (e.g., **moyix**) and maintain it?
2. May I create a new repo with the name **fauxpilot-addon** or **fauxpilot-ext** at https://github.com/moyix/ and maintain it?

I'm personally very interested in open source and free projects like FauxPilot, so I'll do my best to maintain the features or components I submit.

Thank you

**Comment by moyix** [comment]
> First of all, thank you so much for reviewing in detail despite your busy schedule. As you said, I agree to classify it as an add-on project and maintain it. So I would like to suggest two methods as follows.
> 
> 1. Can I create an add-on or ext folder on this org (e.g., **moyix**) and maintain it?

Well, `moyix` isn't an org, it's just my user account :) So it might be better to just have it hosted under your account, e.g. at
https://github.com/leemgs/fauxpilot-webclient

> 2. May I create a new repo with the name **fauxpilot-addon** or **fauxpilot-ext** at https://github.com/moyix/ and maintain it?

Naming it `fauxpilot-addon` or `fauxpilot-ext` implies you would want to put all the 3rd party addons in a single repo. That seems like it would suffer from the same maintenance and management overhead as including it in the main repo?

> I'm personally very interested in open source and free projects like FauxPilot, so I'll do my best to maintain the features or components I submit.
> 
> Thank you

**Comment by leemgs** [comment]
Thank you for your comments. :)
Could you create the below repository to keep the related repositories consistently even though the 'moyix' is an user account (w/o org)?
* https://github.com/moyix/fauxpilot-webclient

**Comment by leemgs** [comment]
@moyix  Could you give me your opinion on twwo method below? Which better?
Option1. https://github.com/fauxpilot/fauxpilot-webclient 
   - I newly created https://github.com/fauxpilot/ newly to combine and unify the FauxPilot-related GitHub repositories. :)
Option2. https://github.com/moyix/fauxpilot-webclient

**Comment by leemgs** [comment]
To reviwers, 
This PR is ready to be merged since the self-assessment is completely done.  😺

**Pull request closed without merging**
