### PR TITLE
Add GitLab VS Code extension

### PR DESCRIPTION
**Pull request by fdegier**
This MR highlights the support for FauxPilot in the GitLab VS Code extension.

### CODE REVIEW

**Comment by fdegier** [comment]
@moyix could you please review this PR?

**Comment by moyix** [comment]
Looks great!

**Comment by michaelfeil** [comment]
@fdegier Does it make sense to add instructions in the markdown on how to configure the GitLab VS Code extension?

**Comment by fdegier** [comment]
It depends, up until version [3.57.3](https://gitlab.com/gitlab-org/gitlab-vscode-extension/compare/v3.57.2...v3.57.3) FauxPilot was supported, see the README for instructions [3.57.3](https://gitlab.com/gitlab-org/gitlab-vscode-extension/compare/v3.57.2...v3.57.3)

But after that version, support for FauxPilot was removed, hopefully support comes back soon.

**Pull request merged**
