### PR TITLE
Make code production ready

### PR DESCRIPTION
**Pull request by fdegier**
Hi @moyix, 

Great work on FauxPilot! I'm an engineer at GitLab and am experimenting with code completions tools, I wanted to give FauxPilot a try and noticed a few things that I thought could be improved for my needs and figured I might as well give back 😄

Changes / updates:
- Use FastAPI instead of Flask for higher performance
- Added Uvicorn to serve a production server instead of a development server
- Upgraded to Python3.10
- Pinned versions of pip packages
- Added Swagger / OpenAPI spec
- Made a few more variables settable via environment variables
- Separated the API from CodeGen proxy, added input model based on OpenAI spec
- Cleaned up code a little bit
- Improved the setup script so it can re-use existing converted models

Let me know what you think, if you have any questions etc.

### CODE REVIEW

**Comment by moyix** [comment]
Wow, this is awesome, and I'm so glad to hear FauxPilot has been useful to your work! :) Let me read through these changes but I'm really excited to see this work on making FauxPilot more usable for production deployments!

**Review by dslandry — APPROVED** [review]

**Comment by dslandry** [comment]
Sorry, the approval it was an error, I was having a look at the code

**Comment by moyix** [comment]
Looks great, thanks for the contribution!

**Comment by fdegier** [comment]
Thanks! I'm curious about future plans you have for FauxPilot.

**Pull request merged**
